### PR TITLE
WIP: Add support for rust-lightning-bitcoinrpc

### PR DESCRIPTION
**Pull request by jtimon**
Even though https://github.com/TheBlueMatt/rust-lightning-bitcoinrpc should not be used in production, it can be used as a tool so that we can test rust-lightning here.

This is not close to be ready.

### CODE REVIEW

**Comment by ariard** [comment]
Hey, I'm almost successful running the test framework. I've dig a little into it, it's using per-implementation fixture to run the test and wait some kind of IPC to talk between fixture and implementation, We are not necessary constrained to use RPC, but I think a foreground process like rust-lightning-bitcoinrpc driven by shell input isn't going to fit.

What's yours thoughts on it ?

**Comment by ariard** [comment]
We may rework rust-lightning-bitcoinrpc in a more daemonic way or go forward on rust-lnd, but I would like to avoid one big daemon and I'm excited by having something like a routerd, a p2pd, a managed, a monitord, and use bitcoind and bitcoin-wallet as backend.

More on it tomorrow :)

**Comment by jtimon** [comment]
Well, my plan was to mimic clightning's rpc to pass the tests, but just
accessing with http (curl or whatever) instead of having an
rust-lightning-cli or whatever.
I'm open to other options, but I thought this was the simplest way to pass
the tests. I don't doubt other architectures could be better for
production, but I working under the assumption that this was just a minimal
daemon to pasd the tests while maintaining the panic to avoid using it in
production and stuff.

You say you almost got it to pass the tests, can I see your branch?
My plan was to start working on the python wrapper for it to pass the tests
next week.

**Comment by jtimon** [comment]
Closing in favor of https://github.com/cdecker/lightning-integration/pull/81

**Pull request closed without merging**
